apiVersion: v1
# pod enable, service account disable (possible issue)
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.16.0
  name: kube-state-metrics
  namespace: monitoring